[build-system]
requires = [ "setuptools >= 35.0.2", "wheel >= 0.29.0", "cython >= 0.29.34,<3.0" ]
build-backend = "setuptools.build_meta"

[tool.black]
target-version = ['py37', 'py38', 'py39', 'py310', 'py311']


[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["."]

[tool.cibuildwheel]
build = "*"
# disabling musllinux until https://github.com/kiwix/kiwix-build/issues/585
# disabling windows until hhttps://github.com/kiwix/kiwix-build/issues/466
# disabling PyPy due to 2 failing tests
skip = "pp* *musllinux* *-win*"

test-requires = ["pytest"]
test-command = "py.test {project}/tests/"

manylinux-x86_64-image = "manylinux_2_28"
manylinux-aarch64-image = "manylinux_2_28"
manylinux-pypy_x86_64-image = "manylinux_2_28"
manylinux-pypy_aarch64-image = "manylinux_2_28"

[tool.cibuildwheel.linux]
archs = ["x86_64", "aarch64"]
# disabling repair as not possible to since libzim is built
# on Ubuntu focal (20.04) with glic 2.31 while the manylinux images on which we
# build the wheels are only avail up to 2.28
# https://github.com/kiwix/kiwix-build/issues/595
repair-wheel-command = ""
# disabling tests as well as unrepaired wheels cant be tested
test-command = ""

[tool.cibuildwheel.macos]
archs = ["x86_64", "arm64"]
