name: test
on: [push]

env:
  LIBZIM_DL_VERSION: "9.2.3-1"
  MACOSX_DEPLOYMENT_TARGET: "12.0"

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
          architecture: x64

      - name: Check formatting and linting
        run: |
          pip install -U invoke
          invoke install-dev
          invoke check

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        python: ["3.12"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
          architecture: x64

      - name: Installing dependencies
        run: pip install -U pip setuptools build

      - name: Building & installing for tests (with profiling)
        env:
          PROFILE: 1
        run: pip install -e .

      - name: move DLLs next to wrapper
        if: matrix.os == 'windows-latest'
        run: |
          dir
          Move-Item -Force -Path .\libzim\*.dll -Destination .\

      - name: Testing
        run: |
          pip install pytest pytest-cov cython
          py.test --cov=libzim --cov-report=term --cov-report term-missing .

      - name: Upload coverage report to codecov
        if: matrix.os == 'ubuntu-22.04' && matrix.python == '3.11'
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
