name: Build sdist and wheels

on:
  pull_request:
  push:
    branches:
      - main

env:
  LIBZIM_DL_VERSION: "2023-12-04"
  MACOSX_DEPLOYMENT_TARGET: "12.0"
  CIBW_ENVIRONMENT_PASS_LINUX: "LIBZIM_DL_VERSION"
  CIBW_BUILD_VERBOSITY: "3"


jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-13]  # windows-2019

    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        if: runner.os == 'Linux'
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.16

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build sdist
        run: pipx run build --sdist

      - uses: actions/upload-artifact@v3
        with:
          path: dist/*.tar.gz
